#include <stdio.h>
#include <stdlib.h>
#include "emulator.h"




int disassemble8080(unsigned char * code_buffer, int pc)
{
	unsigned char * code = &code_buffer[pc];
	int num_bytes = 1;
	FILE* output = stdout;
	switch(*code)
	{
		case 0x00: fprintf(output, "NOP"); break;
		case 0x01: fprintf(output, "LXI B, $%02x%02x", code[2], code[1]); num_bytes = 3;  break;
		case 0x02: fprintf(output, "STAX B"); break;
		case 0x03: fprintf(output, "INX B"); break;
		case 0x04: fprintf(output, "INR B"); break;
		case 0x05: fprintf(output, "DCR B"); break;
		case 0x06: fprintf(output, "MVI B, $%02x", code[1]); num_bytes = 2; break;
		case 0x07: fprintf(output, "RLC"); break;
		case 0x08: fprintf(output, "NOP"); break;
		case 0x09: fprintf(output, "DAD B"); break;
		case 0x0A: fprintf(output, "LDAX B"); break;
		case 0x0B: fprintf(output, "DCX B"); break;
		case 0x0C: fprintf(output, "INR C"); break;
		case 0x0D: fprintf(output, "DCR C"); break;
		case 0x0E: fprintf(output, "MVI C, $%02x", code[1]); num_bytes = 2; break;
		case 0x0F: fprintf(output, "RRC"); break;
		case 0x10: fprintf(output, "NOP"); break;
		case 0x11: fprintf(output, "LXI D, $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0x12: fprintf(output, "STAX D"); break;
		case 0x13: fprintf(output, "INX D"); break;
		case 0x14: fprintf(output, "INR D"); break;
		case 0x15: fprintf(output, "DCR D"); break;
		case 0x16: fprintf(output, "MVI D, $%02x", code[1]); num_bytes = 2; break;
		case 0x17: fprintf(output, "RAL"); break;
		case 0x18: fprintf(output, "NOP"); break;
		case 0x19: fprintf(output, "DAD D"); break;
		case 0x1A: fprintf(output, "LDAX D"); break;
		case 0x1B: fprintf(output, "DCX D"); break;
		case 0x1C: fprintf(output, "INR E"); break;
		case 0x1D: fprintf(output, "DCR E"); break;
		case 0x1E: fprintf(output, "MVI E, $%02x", code[1]); num_bytes = 2; break;
		case 0x1F: fprintf(output, "RAR"); break;
		case 0x20: fprintf(output, "RIM"); break;
		case 0x21: fprintf(output, "LXI H, $%02x%02x", code[2], code[1]); num_bytes = 3;  break;
		case 0x22: fprintf(output, "SHLD $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0x23: fprintf(output, "INX H"); break;
		case 0x24: fprintf(output, "INR H"); break; 
		case 0x25: fprintf(output, "DCR H"); break;
		case 0x26: fprintf(output, "MVI H, $%02x",code[1]); num_bytes = 2; break;
		case 0x27: fprintf(output, "DAA"); break;
		case 0x28: fprintf(output, "NOP"); break;
		case 0x29: fprintf(output, "DAD H"); break;
		case 0x2A: fprintf(output, "LHLD $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0x2B: fprintf(output, "DCX H"); break;
		case 0x2C: fprintf(output, "INR L"); break;
		case 0x2D: fprintf(output, "DCR L"); break;
		case 0x2E: fprintf(output, "MVI L, $%02x", code[1]); num_bytes = 2; break;
		case 0x2F: fprintf(output, "CMA"); break;
		case 0x30: fprintf(output, "SIM"); break;
		case 0x31: fprintf(output, "LXI SP, $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0x32: fprintf(output, "STA $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0x33: fprintf(output, "INX SP"); break;
		case 0x34: fprintf(output, "INR M"); break;
		case 0x35: fprintf(output, "DCR M"); break;
		case 0x36: fprintf(output, "MVI M, $%02x", code[1]); num_bytes = 2; break;
		case 0x37: fprintf(output, "STC"); break;
		case 0x38: fprintf(output, "NOP"); break;
		case 0x39: fprintf(output, "DAD SP"); break;
		case 0x3A: fprintf(output, "LDA $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0x3B: fprintf(output, "DCX SP"); break;
		case 0x3C: fprintf(output, "INR A"); break;
		case 0x3D: fprintf(output, "DCR A"); break;
		case 0x3E: fprintf(output, "MVI A, %02x", code[1]); num_bytes = 2; break;
		case 0x3F: fprintf(output, "CMC"); break;
		case 0x40: fprintf(output, "MOV B, B"); break;
		case 0x41: fprintf(output, "MOV B, C"); break;
		case 0x42: fprintf(output, "MOV B, D"); break;
		case 0x43: fprintf(output, "MOV B, E"); break;
		case 0x44: fprintf(output, "MOV B, H"); break;
		case 0x45: fprintf(output, "MOV B, L"); break;
		case 0x46: fprintf(output, "MOV B, M"); break;
		case 0x47: fprintf(output, "MOV B, A"); break;
		case 0x48: fprintf(output, "MOV C, B"); break;
		case 0x49: fprintf(output, "MOV C, C"); break;
		case 0x4A: fprintf(output, "MOV C, D"); break;
		case 0x4B: fprintf(output, "MOV C, E"); break;
		case 0x4C: fprintf(output, "MOV C, H"); break;
		case 0x4D: fprintf(output, "MOV C, L"); break;
		case 0x4E: fprintf(output, "MOV C, M"); break;
		case 0x4F: fprintf(output, "MOV C, A"); break;
		case 0x50: fprintf(output, "MOV D, B"); break;
		case 0x51: fprintf(output, "MOV D, C"); break;
		case 0x52: fprintf(output, "MOV D, D"); break;
		case 0x53: fprintf(output, "MOV D, E"); break;
		case 0x54: fprintf(output, "MOV D, H"); break;
		case 0x55: fprintf(output, "MOV D, L"); break;
		case 0x56: fprintf(output, "MOV D, M"); break;
		case 0x57: fprintf(output, "MOV D, A"); break;
		case 0x58: fprintf(output, "MOV E, B"); break;
		case 0x59: fprintf(output, "MOV E, C"); break;
		case 0x5A: fprintf(output, "MOV E, D"); break;
		case 0x5B: fprintf(output, "MOV E, E"); break;
		case 0x5C: fprintf(output, "MOV E, H"); break;
		case 0x5D: fprintf(output, "MOV E, L"); break;
		case 0x5E: fprintf(output, "MOV E, M"); break;
		case 0x5F: fprintf(output, "MOV E, A"); break;
		case 0x60: fprintf(output, "MOV H, B"); break;
		case 0x61: fprintf(output, "MOV H, C"); break;
		case 0x62: fprintf(output, "MOV H, D"); break;
		case 0x63: fprintf(output, "MOV H, E"); break;
		case 0x64: fprintf(output, "MOV H, H"); break;
		case 0x65: fprintf(output, "MOV H, L"); break;
		case 0x66: fprintf(output, "MOV H, M"); break;
		case 0x67: fprintf(output, "MOV H, A"); break;
		case 0x68: fprintf(output, "MOV L, B"); break;
		case 0x69: fprintf(output, "MOV L, C"); break;
		case 0x6A: fprintf(output, "MOV L, D"); break;
		case 0x6B: fprintf(output, "MOV L, E"); break;
		case 0x6C: fprintf(output, "MOV L, H"); break;
		case 0x6D: fprintf(output, "MOV L, L"); break; 
		case 0x6E: fprintf(output, "MOV L, M"); break;
		case 0x6F: fprintf(output, "MOV L, A"); break;
		case 0x70: fprintf(output, "MOV M, B"); break;
		case 0x71: fprintf(output, "MOV M, C"); break;
		case 0x72: fprintf(output, "MOV M, D"); break;
		case 0x73: fprintf(output, "MOV M, E"); break;
		case 0x74: fprintf(output, "MOV M, H"); break;
		case 0x75: fprintf(output, "MOV M, M"); break;
		case 0x76: fprintf(output, "HLT"); break;
		case 0x77: fprintf(output, "MOV M, A"); break;
		case 0x78: fprintf(output, "MOV A, B"); break;
		case 0x79: fprintf(output, "MOV A, C"); break;
		case 0x7A: fprintf(output, "MOV A, D"); break;
		case 0x7B: fprintf(output, "MOV A, E"); break;
		case 0x7C: fprintf(output, "MOV A, H"); break;
		case 0x7D: fprintf(output, "MOV A, L"); break;
		case 0x7E: fprintf(output, "MOV A, M"); break;
		case 0x7F: fprintf(output, "MOV A, A"); break;
		case 0x80: fprintf(output, "ADD B"); break;
		case 0x81: fprintf(output, "ADD C"); break;
		case 0x82: fprintf(output, "ADD D"); break;
		case 0x83: fprintf(output, "ADD E"); break;
		case 0x84: fprintf(output, "ADD H"); break;
		case 0x85: fprintf(output, "ADD L"); break;
		case 0x86: fprintf(output, "ADD M"); break;
		case 0x87: fprintf(output, "ADD A"); break;
		case 0x88: fprintf(output, "ADC B"); break;
		case 0x89: fprintf(output, "ADC C"); break;
		case 0x8A: fprintf(output, "ADC D"); break;
		case 0x8B: fprintf(output, "ADC E"); break;
		case 0x8C: fprintf(output, "ADC H"); break;
		case 0x8D: fprintf(output, "ADC L"); break;
		case 0x8E: fprintf(output, "ADC M"); break;
		case 0x8F: fprintf(output, "ADC A"); break;
		case 0x90: fprintf(output, "SUB B"); break;
		case 0x91: fprintf(output, "SUB C"); break;
		case 0x92: fprintf(output, "SUB D"); break;
		case 0x93: fprintf(output, "SUB E"); break;
		case 0x94: fprintf(output, "SUB H"); break;
		case 0x95: fprintf(output, "SUB L"); break;
		case 0x96: fprintf(output, "SUB M"); break;
		case 0x97: fprintf(output, "SUB A"); break;
		case 0x98: fprintf(output, "SBB B"); break;
		case 0x99: fprintf(output, "SBB C"); break;
		case 0x9A: fprintf(output, "SBB D"); break;
		case 0x9B: fprintf(output, "SBB E"); break;
		case 0x9C: fprintf(output, "SBB H"); break;
		case 0x9D: fprintf(output, "SBB L"); break;
		case 0x9E: fprintf(output, "SBB M"); break;
		case 0x9F: fprintf(output, "SBB A"); break;
		case 0xA0: fprintf(output, "ANA B"); break;
		case 0xA1: fprintf(output, "ANA C"); break;
		case 0xA2: fprintf(output, "ANA D"); break;
		case 0xA3: fprintf(output, "ANA E"); break;
		case 0xA4: fprintf(output, "ANA H"); break;
		case 0xA5: fprintf(output, "ANA L"); break;
		case 0xA6: fprintf(output, "ANA M"); break;
		case 0xA7: fprintf(output, "ANA A"); break;
		case 0xA8: fprintf(output, "XRA B"); break;
		case 0xA9: fprintf(output, "XRA C"); break;
		case 0xAA: fprintf(output, "XRA D"); break;
		case 0xAB: fprintf(output, "XRA E"); break;
		case 0xAC: fprintf(output, "XRA H"); break;
		case 0xAD: fprintf(output, "XRA L"); break;
		case 0xAE: fprintf(output, "XRA M"); break;
		case 0xAF: fprintf(output, "XRA A"); break;
		case 0xB0: fprintf(output, "ORA B"); break;
		case 0xB1: fprintf(output, "ORA C"); break;
		case 0xB2: fprintf(output, "ORA D"); break;
		case 0xB3: fprintf(output, "ORA E"); break;
		case 0xB4: fprintf(output, "ORA H"); break;
		case 0xB5: fprintf(output, "ORA L"); break;
		case 0xB6: fprintf(output, "ORA M"); break;
		case 0xB7: fprintf(output, "ORA A"); break;
		case 0xB8: fprintf(output, "CMP B"); break;
		case 0xB9: fprintf(output, "CMP C"); break;
		case 0xBA: fprintf(output, "CMP D"); break;
		case 0xBB: fprintf(output, "CMP E"); break;
		case 0xBC: fprintf(output, "CMP H"); break;
		case 0xBD: fprintf(output, "CMP L"); break;
		case 0xBE: fprintf(output, "CMP M"); break;
		case 0xBF: fprintf(output, "CMP A"); break;
		case 0xC0: fprintf(output, "RNZ"); break;
		case 0xC1: fprintf(output, "POP B"); break;
		case 0xC2: fprintf(output, "JNZ $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xC3: fprintf(output, "JMP $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xC4: fprintf(output, "CNZ $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xC5: fprintf(output, "PUSH B"); break;
		case 0xC6: fprintf(output, "ADI $%02x", code[1]); num_bytes = 2; break;
		case 0xC7: fprintf(output, "RST 0"); break;
		case 0xC8: fprintf(output, "RZ"); break;
		case 0xC9: fprintf(output, "RET"); break;
		case 0xCA: fprintf(output, "JZ $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xCB: fprintf(output, "NOP"); break;
		case 0xCC: fprintf(output, "CZ $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xCD: fprintf(output, "CALL $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xCE: fprintf(output, "ACI $%02x", code[1]); num_bytes = 2; break;
		case 0xCF: fprintf(output, "RST 1"); break;
		case 0xD0: fprintf(output, "RNC"); break;
		case 0xD1: fprintf(output, "POP D"); break;
		case 0xD2: fprintf(output, "JNC $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xD3: fprintf(output, "OUT $%02x", code[1]); num_bytes = 2; break;
		case 0xD4: fprintf(output, "CNC $%02x%02x", code[2], code[1]); num_bytes = 3; break;
		case 0xD5: fprintf(output, "PUSH D"); break;
		case 0xD6: fprintf(output, "SUI $%02x", code[1]); num_bytes = 2; break;
		case 0xD7: fprintf(output, "RST 2"); break;
		case 0xD8: fprintf(output, "RC"); break;
		case 0xD9: fprintf(output, "NOP"); break;
		case 0xDA: fprintf(output, "JC $%02x", code[1]); num_bytes = 2; break;
		case 0xDB: fprintf(output, "IN $%02x", code[1]); num_bytes = 2; break;
		case 0xDC: fprintf(output, "CC $%02x", code[1]); num_bytes = 2; break;
		case 0xDD: fprintf(output, "NOP"); break;
		case 0xDE: fprintf(output, "SBI $%02x", code[1]); num_bytes = 2; break;
		case 0xDF: fprintf(output, "RST 3"); break;
		case 0xE0: fprintf(output, "RPO"); break;
		case 0xE1: fprintf(output, "POP H"); break;
		case 0xE2: fprintf(output, "JPO $%02x", code[1]); num_bytes = 2; break;
		case 0xE3: fprintf(output, "XTHL"); break;
		case 0xE4: fprintf(output, "CPO $%02x", code[1]); num_bytes = 2; break;
		case 0xE5: fprintf(output, "PUSH H"); break;
		case 0xE6: fprintf(output, "ANI $%02x", code[1]); num_bytes = 2; break;
		case 0xE7: fprintf(output, "RST 4"); break;
		case 0xE8: fprintf(output, "RPE"); break;
		case 0xE9: fprintf(output, "PCHL"); break;
		case 0xEA: fprintf(output, "JPE $%02x", code[1]); num_bytes = 2; break;
		case 0xEB: fprintf(output, "XCHG"); break;
		case 0xEC: fprintf(output, "CPE $%02x", code[1]); num_bytes = 2; break;
		case 0xED: fprintf(output, "NOP"); break;
		case 0xEE: fprintf(output, "XRI $%02x", code[1]); num_bytes = 2; break;
		case 0xEF: fprintf(output, "RST 5"); break;
		case 0xF0: fprintf(output, "RP"); break;
		case 0xF1: fprintf(output, "POP PSW"); break;
		case 0xF2: fprintf(output, "JP $%02x", code[1]); num_bytes = 2; break;
		case 0xF3: fprintf(output, "DI"); break;
		case 0xF4: fprintf(output, "CP $%02x", code[1]); num_bytes = 2; break;
		case 0xF5: fprintf(output, "PUSH PSW"); break;
		case 0xF6: fprintf(output, "ORI D8"); break;
		case 0xF7: fprintf(output, "RST 6"); break;
		case 0xF8: fprintf(output, "RM"); break;
		case 0xF9: fprintf(output, "SPHL"); break;
		case 0xFA: fprintf(output, "JM $%02x", code[1]); num_bytes = 2; break;
		case 0xFB: fprintf(output, "EI"); break;
		case 0xFC: fprintf(output, "CM $%02x", code[1]); num_bytes = 2; break;
		case 0xFD: fprintf(output, "NOP"); break;
		case 0xFE: fprintf(output, "CPI $%02x", code[1]); num_bytes = 2; break;
		case 0xFF: fprintf(output, "RST 7"); break;
	}

	fprintf(output, "\n");
	
	return num_bytes;
}
